# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6609d9654683ef8ca4baf9747f6ea3721a0dae4bd03024e07555c4ca1b738b28e1443f8debbc186f0babd669128782f577ad88c3ee7520c9bc13ae145b8398a4

test:
  secret_key_base: 93ae2723ed0a87f647f8609196b09ebfea94a5e43add2e4029de077eafcf8b6846815f9cdc3ef833293650fcc56a8e77efaed49c24e39db7f96ae3c573796dee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
